const PDFDocument = require("pdfkit");
const fs = require("fs");
const path = require("path");

const ticketsDir =
    path.join(__dirname, "../tickets");

if (!fs.existsSync(ticketsDir)) {
    fs.mkdirSync(ticketsDir, {
        recursive: true
    });
}

const generateTicketPdf = (
    booking,
    event,
    user
) => {

    return new Promise((resolve, reject) => {

        const filePath =
            path.join(
                ticketsDir,
                `${booking.ticketId}.pdf`
            );

        const doc =
            new PDFDocument({
                size: "A4",
                margin: 40
            });

        const stream =
            fs.createWriteStream(
                filePath
            );

        stream.on(
            "error",
            reject
        );

        doc.pipe(stream);

        // Background Card
        doc.roundedRect(
            30,
            30,
            535,
            720,
            15
        )
        .fillAndStroke(
            "#111111",
            "#8B5CF6"
        );

        // Header
        doc.fillColor("#FFFFFF");

        doc.fontSize(28)
           .text(
                "EVENTLY",
                0,
                55,
                {
                    align: "center"
                }
            );

        doc.fontSize(12)
           .fillColor("#A855F7")
           .text(
                "DIGITAL EVENT PASS",
                {
                    align: "center"
                }
            );

        // Event Title
        doc.moveDown(2);

        doc.fillColor("#FFFFFF");

        doc.fontSize(22)
           .text(
                event.title,
                {
                    align: "center"
                }
            );

        // Details Box
        doc.roundedRect(
            60,
            180,
            475,
            220,
            10
        )
        .stroke("#8B5CF6");

        doc.fontSize(14);

        doc.fillColor("#A855F7")
           .text(
                "ATTENDEE",
                85,
                205
            );

        doc.fillColor("#FFFFFF")
           .text(
                user.name,
                85,
                225
            );

        doc.fillColor("#A855F7")
           .text(
                "TICKET ID",
                85,
                270
            );

        doc.fillColor("#FFFFFF")
           .text(
                booking.ticketId,
                85,
                290
            );

        doc.fillColor("#A855F7")
           .text(
                "DATE",
                85,
                335
            );

        doc.fillColor("#FFFFFF")
           .text(
                new Date(
                    event.date
                ).toLocaleDateString(),
                85,
                355
            );

        doc.fillColor("#A855F7")
           .text(
                "VENUE",
                300,
                205
            );

        doc.fillColor("#FFFFFF")
           .text(
                event.location ||
                event.venue,
                300,
                225,
                {
                    width: 180
                }
            );

        doc.fillColor("#A855F7")
           .text(
                "TICKETS",
                300,
                270
            );

        doc.fillColor("#FFFFFF")
           .text(
                booking.tickets.toString(),
                300,
                290
            );

        doc.fillColor("#A855F7")
           .text(
                "AMOUNT",
                300,
                335
            );

        doc.fillColor("#FFFFFF")
           .text(
                `₹${booking.totalPrice}`,
                300,
                355
            );

        // QR Title
        doc.fontSize(16)
           .fillColor("#FFFFFF")
           .text(
                "SCAN FOR ENTRY",
                0,
                450,
                {
                    align: "center"
                }
            );

        // QR Image
        const qrBuffer =
            Buffer.from(
                booking.qrCode.split(",")[1],
                "base64"
            );

        doc.image(
            qrBuffer,
            210,
            490,
            {
                width: 150
            }
        );

        // Footer
        doc.fontSize(10)
           .fillColor("#BBBBBB")
           .text(
                "Present this QR code at the event entrance.",
                0,
                675,
                {
                    align: "center"
                }
            );

        doc.text(
            "Generated by Evently",
            {
                align: "center"
            }
        );

        doc.end();

        stream.on(
            "finish",
            () => resolve(filePath)
        );

    });

};

module.exports =
    generateTicketPdf;